name: valida_generator
description: Code generator for valida. Create field, params and object validators from code annotations.
version: 0.2.1
homepage: https://github.com/juancastillo0/valida

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  analyzer: ">=5.0.0 <7.0.0"
  build: ^2.0.0
  dart_style: ^2.0.0
  glob: ^2.0.0
  path: ^1.0.0
  source_gen: ^1.0.0
  valida: ^0.2.0

dev_dependencies:
  build_config: ^1.0.0
  build_runner: ^2.0.0
  lint: ^2.1.2
  test: ^1.0.0
